export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ORGANIZATION_ROUTE = '/organization'
export const MAIN_ROUTE = '/'